import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/componants/header/Header";
import Footer from "@/componants/Footer";
import Navbar from "@/componants/header/Navber";
import Header3 from "@/componants/header/Header3";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <div className="sticky top-0 z-50">
          <Header3></Header3>
          <Navbar></Navbar>
        </div>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
